version: '3.7'

services:

  s-postgres:
    image: postgres
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    # env_file:
      # - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: password
      # ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: logicaldoc
      # ${DB_NAME}
      MYSQL_USER: logicaldoc
      # {DB_USER}
      MYSQL_PASSWORD: password
      # ${DB_PASSWORD}
            
  logicaldoc-pg:
    image: mylogcialdoc
    links:
      - s-postgres:hostpg